apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ../../base
  - secret.enc.yaml
images:
  - name: ghcr.io/calebsargeant/fortivpn-gateway-cookie
    newTag: v1.0.20 # {"$imagepolicy": "flux-system:cookie:tag"}
  - name: ghcr.io/calebsargeant/fortivpn-gateway-vpn
    newTag: v1.0.20 # {"$imagepolicy": "flux-system:vpn:tag"}
  - name: ghcr.io/calebsargeant/fortivpn-gateway-bgp
    newTag: v1.0.20 # {"$imagepolicy": "flux-system:bgp:tag"}
