apiVersion: v1
kind: Secret
metadata:
    name: fortivpn-credentials
    namespace: networking
type: Opaque
stringData:
    #ENC[AES256_GCM,data:zYILvxaZwfokUHcWiS2iRDy0T8D8y46x,iv:BfHWavnxZqdWVSuxEYk/kuzd0FyyPX0aZPyqdkahA8k=,tag:VTicwriCpjKIZ2Udqzw0Nw==,type:comment]
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:TZFpyQqwlLmrWEDkUimeJpeST+Z4SDhc28XJgzHRlZBDQ9v+JrSzvn8Xj9jnlgAArKUJ6kCxQTZYAfJujj4VranlTbAaVWQWo68yuxj3HkrWorutyZHf0aANzgK5w770uw2GVuJkltmyP4KFiG1TzqzFEDX7mc112fr/l9cYMv4l8Ps3K9MHqireD+UALazvPwU2o7/IQPftS3WJhF7cSkbsCuORzdurNX5YVi9PYd6wA5586Lt0fEWg4s2YwBm8E1jMXCBI6isU71FYt9JlgYfc0H9EjSL420SaU0sIR+OewFfVLgfgsiVh5AcLsU7M/S3VDm14z2fWQ2XNxs1D9P8SKufI9L6M72FcKPYflNr40AOBPiOqpxCWXUg8KwlAKqhYJeEq4H7aQGj3KveLvjct5TeJao+ZymbBj+Gflyhr8SFsBAsb02ZYit66n4yQRbpzbxOUF5r+AQdMQw4FoVy0l7MxyNaGCAS2uLMrtAoRiUUtuZ0AnU/j6+IFNUW4nbFiezJpEp+CqQuIDXr8VS7umJeyJ4xRBYOuCcalQPwOtX41tK/2tsYDqT8cbVl9ZPfOycQKPUcWEBqejfb1PQrsozOaWSIQv9kB89n3EZZscUvz+cInBsUMsaSVkrygfTy9kFQgQ8Nfqe94oDN6f8EnoYMLdsSKH40oIBZMs6O09CdbDbYNtrtvI3uvSkpZMp7gysWXpSEo9gwMWqqHaYD73VBLIZ/x28dNw+Le+99twSZD10+RGqhXsALlQoUPMIqgZ+ZAx9LVVFNQSNSe+zymatJO6DIe/rQVETDK+zJJaJDeOf3y+Ic58Rem+AW9KwHSvEMYy+sBy3Bl9YwvrNXGFIlXlnXkOFu3B8xadIEEvcjgiQtRExE1jc4g6JCcfOde0g7/JE8JKR2/XgMZvL8CvU8Ii/BlKk44C8rh7JUAXKhM48vtSDNRIo1lb2+gx4YTfsWQM17NjeAUPf0Vg8BY8PkjggLWCAJH/k6sriBBl52Nf8D8EHPvtT96NhitgeaN/FRo997laGGMNfGgT51ny6vcdd8XA0EwpY7TzIK1F8gRY1xl3onJBwvXZ6z1sSCBM1pftxlkn64+O7/mLNFchRzZFPcbtGuY3j3ha94V2Mmd,iv:phC2Qy+2JEMEIt9YCSWq0sX0WXyaj1Ywuje+pgCQimw=,tag:H6uNgK2QNB6aGkiyNZyjlg==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:6ixVNwX78+/l,iv:V2fxlHUqWJdYafBcnfdIoJXZGqRjkvJD3gMSV5bX9Gc=,tag:f7bewluFDvGw5Zcwdlm7Ew==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:jM/TvJZVOsjZeU7A,iv:XEpUq8LS5bU2nGg2M/12KwrAQAxhaWq/1ea+WTV8x/w=,tag:Sd0C3WLuy3xsMEz2aWx8DQ==,type:str]
    #ENC[AES256_GCM,data:0O3Hi9TcXkPoMqAPIzw5LmJP,iv:r6H34JBxaqTDiOGBI2Z7kP6B0H25wyR2l3OLrtS5yus=,tag:JAwWzdhKpPj+cj0IUTm7nQ==,type:comment]
    VPN_GATEWAY: ENC[AES256_GCM,data:Mwj6oNsaFUGco82I64GBjg==,iv:dGLMzZ7ClZbS1WV7z+WZ/FPXRRvpTkafGWVlC2DuR5Q=,tag:XzjYqPzOomq/NgBb/8pq4A==,type:str]
    VPN_PORT: ENC[AES256_GCM,data:SPb5,iv:Ci6cl2n8xEsz5WMnL7CXZn/dSBqRGmkdwqy+NpJieVM=,tag:8fkQ3YWJH7ffsHo+DEFc5Q==,type:str]
    #ENC[AES256_GCM,data:TWQpUiUlWNtBnQg0q38lZAvh,iv:r60NuKNYuUit3nVIWS9DU6x99dF3oNGJjKlNOxXv0Ns=,tag:GobEEGOGRgWagNKLzDbIdg==,type:comment]
    #ENC[AES256_GCM,data:BBlMzWtCcEO6FoLN3vmLFeW5sVCPQGoslmn0Z6pJyoFv31Y=,iv:ELV50Er8qlcYsScXykjFBLWDYxsBjX2KnlsaaBrZrtQ=,tag:t2hrLQfn2XK9hSqWutMKBg==,type:comment]
    BGP_ROUTER_ID: ENC[AES256_GCM,data:fIEj/lPgRz63TCWtrA==,iv:dJLaOEwhsNNWcP6IxZzcsZvk4PnMogCrKi7+Scaiass=,tag:7tSKq6URgVrwj+7Ig42D7g==,type:str]
    #ENC[AES256_GCM,data:gnsfI27zpuUEL9t035mt2D5XhLyWBR8=,iv:X7dnx6hZ68CSxWkMkVK25FAqipJa80zFKz1Xo4zWyD8=,tag:SoBPOVQ9cLmmGG+wyAUkjQ==,type:comment]
    BGP_LOCAL_AS: ENC[AES256_GCM,data:YJ8sFjU=,iv:sFHv3e7YsOK6lAhiTW7jsZ6oSc9BwAwQBZiPpgrwd2Q=,tag:PyBpnOdfL75xX1Rwvoy6Ug==,type:str]
    #ENC[AES256_GCM,data:39losC/Sgxx9MnGFTsLuASLgmY8x4pq9,iv:BG4p/mSrPmgu/tSvdkspH5Kq0zWVqoUbw5pt79sFV9o=,tag:cmxRx67QV3CFcqBN4vlZeA==,type:comment]
    BGP_NEIGHBOR_IP: ENC[AES256_GCM,data:JSfpZEVTcXsWceX+,iv:Atv6MDaBl+OH/L1u9b3yGBai3veDh8lCVIQ/DmNileM=,tag:W4g0Y1ErSh2fsPKcrHa+Ew==,type:str]
    #ENC[AES256_GCM,data:5k0uwtUUNoEGAs2XOf4kfvnR/kDohrlx,iv:wvPAbeJ5KQQMGprIaGZAWn90Rm3ReZi+3vOi8nzpvWY=,tag:SqyeESbOyjF3+eKtIb2Bqg==,type:comment]
    BGP_NEIGHBOR_AS: ENC[AES256_GCM,data:rp742OM=,iv:hH+DfwPxoDlNgsuKZDijcSlHi/ngZSbqqfbOUbich2Y=,tag:xdbX8yQB2wooebJ0R4p1pQ==,type:str]
    TRUSTED_CERT: ENC[AES256_GCM,data:RvYVmMR+509/bDOmWLu1fVTQgmIjwZ23VI5sp9ihUYSHs0jPJMOOehKe7t7geKIWDLwQOmBZxgQRn11X+vvv,iv:MggXt4BuZk6MZDkkPp+qLa1kWo8tjSToNUEpM0lnCEg=,tag:q8m57xLpqUcsVLKlVGfirA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RjNDemx1NWxLMzhrcy9a
            Mlppb1lsSzlyMkR0U1FvTThrWGhUNVJGSUhrCnJ4eHNOenIrRlVld0dnM1NDa050
            UHl4SitXUHdRMGs0QllLRHErWkNZZGsKLS0tIDFoTXNlSkZRdkxBUWZjVWd6QzVh
            ZmVnSFBseXNVeEFGMkdwYk5RbHlYWG8Kr7j6PCIVA1wuV0pFag3CIHs6mje3TkQa
            soQjG5/X5JRVGzu76DCGWRaCTfe9wqCzbYFOoR+Mu5T36/PFFYrypg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T19:04:42Z"
    mac: ENC[AES256_GCM,data:6tb2NTjDjFd1FvfvSBu+MDqTdasuAikAATjCrYpD+Hw2oUuv+IupcmzDhhqzznP15jjzkHPI+pNQ3kwOQw0Ff3LlkzLcQZOwerbWntyx42jDY8yEL7KRJoZQtcoGOYmb5eo9Q+gAhu8Nm6IcbCenxnjxqfP5gea9cHlBVdXxVTg=,iv:26UOzZm8eOOjHNophW6h3oY+WCXzlOBt21XJ5xKk60A=,tag:JYZQ/fBrA4YTT6KRpX485w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
